### ISSUE TITLE
java.io.IOException when loading Seasonal Forecasts

### ISSUE THREAD

**Issue by matteodefelice** [SantanderMetGroup/loadeR#16]
Here the code: 

```
loginUDG("matteodefelice", "***")
years = 1983:2007
lonlim = c(-10, 40)
latlim = c(20, 50)
LEAD_TIME = 1
SEASON = 'JJA'
MONTHS = c(6, 7, 8)
varname = 'tas'

fcst = loadECOMS(dataset = "System4_seasonal_15", var = varname, members = 1, 
                 lonLim = lonlim, latLim = latlim, season = MONTHS, 
                 years = years, leadMonth = LEAD_TIME)
```

Here the output:

```
[2016-09-14 09:29:58] Defining homogeneization parameters for variable "tas"
[2016-09-14 09:29:58] Opening dataset...
[2016-09-14 09:34:55] The dataset was successfuly opened
[2016-09-14 09:34:55] Defining geo-location parameters
[2016-09-14 09:34:55] Defining initialization time parameters
[2016-09-14 09:34:59] Retrieving data subset ...
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at opendap.dap.DVector.deserialize(DVector.java:240)
    at opendap.dap.DataDDS.readData(DataDDS.java:135)
    at opendap.dap.DConnect2$DataDDSCommand.process(DConnect2.java:901)
    at opendap.dap.DConnect2.openConnection(DConnect2.java:314)
    at opendap.dap.DConnect2.getData(DConnect2.java:872)
    at opendap.dap.DConnect2.getData(DConnect2.java:1172)
    at ucar.nc2.dods.DODSNetcdfFile.readDataDDSfromServer(DODSNetcdfFile.java:1488)
    at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1659)
    at ucar.nc2.Variable.reallyRead(Variable.java:907)
    at ucar.nc2.Variable._read(Variable.java:892)
    at ucar.nc2.Variable.read(Variable.java:703)
    at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
    at ucar.nc2.SectionReader.reallyRead(SectionReader.java:61)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
    at ucar.nc2.Variable.read(Variable.java:703)
    at ucar.nc2.Variable.read(Variable.java:649)
    at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at RJavaTools.invokeMethod(RJavaTools.java:386)
opendap.dap.DAP2Exception: java.io.EOFException
    at opendap.dap.DConnect2.openConnection(DConnect2.java:319)
    at opendap.dap.DConnect2.getData(DConnect2.java:872)
    at opendap.dap.DConnect2.getData(DConnect2.java:1172)
    at ucar.nc2.dods.DODSNetcdfFile.readDataDDSfromServer(DODSNetcdfFile.java:1488)
    at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1659)
    at ucar.nc2.Variable.reallyRead(Variable.java:907)
    at ucar.nc2.Variable._read(Variable.java:892)
    at ucar.nc2.Variable.read(Variable.java:703)
    at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
    at ucar.nc2.SectionReader.reallyRead(SectionReader.java:61)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
    at ucar.nc2.Variable.read(Variable.java:703)
    at ucar.nc2.Variable.read(Variable.java:649)
    at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at RJavaTools.invokeMethod(RJavaTools.java:386)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at opendap.dap.DVector.deserialize(DVector.java:240)
    at opendap.dap.DataDDS.readData(DataDDS.java:135)
    at opendap.dap.DConnect2$DataDDSCommand.process(DConnect2.java:901)
    at opendap.dap.DConnect2.openConnection(DConnect2.java:314)
    ... 20 more
Sep 14, 2016 9:41:02 AM ucar.nc2.dt.grid.GeoGrid readDataSlice
SEVERE: GeoGrid.getdataSlice() on variable t2m dataset dods://www.meteo.unican.es/tds5/dodsC/system4/System4_Seasonal_15Members.ncml
java.io.IOException: java.io.EOFException; t2m -- 64:64,0:0,124:491,53:93,467:479
    at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1665)
    at ucar.nc2.Variable.reallyRead(Variable.java:907)
    at ucar.nc2.Variable._read(Variable.java:892)
    at ucar.nc2.Variable.read(Variable.java:703)
    at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
    at ucar.nc2.SectionReader.reallyRead(SectionReader.java:61)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507)
    at ucar.nc2.dataset.VariableDS._read(VariableDS.java:531)
    at ucar.nc2.Variable.read(Variable.java:703)
    at ucar.nc2.Variable.read(Variable.java:649)
    at ucar.nc2.dt.grid.GeoGrid.readDataSlice(GeoGrid.java:606)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at RJavaTools.invokeMethod(RJavaTools.java:386)

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException: java.io.IOException: java.io.EOFException; t2m -- 64:64,0:0,124:491,53:93,467:479
```

All the packages from the master branch.

**Comment by jbedia** [comment]
Looks like a temporary server error. The dataset mentioned is working fine to date.
